spring.application.name=backend

IMAGE_PRIVATE_KEY=private_JmT9h7MQIeWd6B07sV2EUXacSBo=

gemini.api.key=AIzaSyDPnx5Vdv1kzVyZ_WJ5hw7ZwLqUp8vKIoY
gemini.base.url=https://generativelanguage.googleapis.com/v1beta/openai/
gemini.model=gemini-2.5-flash



server.port=8081

### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/BD?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Baccouch10
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

### JWT ###
jwt.secret=randomSecretKeyForJWTGenerationThatIsLongEnough1230000000000000000!
